#!/usr/bin/env node
// Run against production: DATABASE_URL="..." node scripts/seed-players.js
// Or locally: node scripts/seed-players.js

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const players = [
  // ── ALGERIA ──
  { name: "Raïs M'Bolhi", country: "Algeria", position: "GK", number: 1 },
  { name: "Alexandre Oukidja", country: "Algeria", position: "GK", number: 16 },
  { name: "Aïmen Mahious", country: "Algeria", position: "GK", number: 23 },
  { name: "Ramy Bensebaini", country: "Algeria", position: "DEF", number: 3 },
  { name: "Aïssa Mandi", country: "Algeria", position: "DEF", number: 4 },
  { name: "Djamel Benlamri", country: "Algeria", position: "DEF", number: 5 },
  { name: "Mehdi Zeffane", country: "Algeria", position: "DEF", number: 2 },
  { name: "Youcef Atal", country: "Algeria", position: "DEF", number: 22 },
  { name: "Djaouad Belaïli", country: "Algeria", position: "MID", number: 7 },
  { name: "Ismaël Bennacer", country: "Algeria", position: "MID", number: 8 },
  { name: "Sofiane Feghouli", country: "Algeria", position: "MID", number: 10 },
  { name: "Hossem Aouar", country: "Algeria", position: "MID", number: 18 },
  { name: "Said Benrahma", country: "Algeria", position: "MID", number: 15 },
  { name: "Nabil Bentaleb", country: "Algeria", position: "MID", number: 17 },
  { name: "Riyad Mahrez", country: "Algeria", position: "FWD", number: 9 },
  { name: "Islam Slimani", country: "Algeria", position: "FWD", number: 11 },
  { name: "Baghdad Bounedjah", country: "Algeria", position: "FWD", number: 19 },
  { name: "Youcef Belaïli", country: "Algeria", position: "FWD", number: 13 },
  { name: "Adam Ounas", country: "Algeria", position: "FWD", number: 20 },

  // ── ARGENTINA ──
  { name: "Emiliano Martínez", country: "Argentina", position: "GK", number: 23 },
  { name: "Franco Armani", country: "Argentina", position: "GK", number: 1 },
  { name: "Gerónimo Rulli", country: "Argentina", position: "GK", number: 12 },
  { name: "Nahuel Molina", country: "Argentina", position: "DEF", number: 26 },
  { name: "Gonzalo Montiel", country: "Argentina", position: "DEF", number: 13 },
  { name: "Nicolás Otamendi", country: "Argentina", position: "DEF", number: 19 },
  { name: "Cristian Romero", country: "Argentina", position: "DEF", number: 27 },
  { name: "Lisandro Martínez", country: "Argentina", position: "DEF", number: 25 },
  { name: "Marcos Acuña", country: "Argentina", position: "DEF", number: 8 },
  { name: "Nicolás Tagliafico", country: "Argentina", position: "DEF", number: 3 },
  { name: "Germán Pezzella", country: "Argentina", position: "DEF", number: 6 },
  { name: "Rodrigo De Paul", country: "Argentina", position: "MID", number: 7 },
  { name: "Leandro Paredes", country: "Argentina", position: "MID", number: 5 },
  { name: "Alexis Mac Allister", country: "Argentina", position: "MID", number: 20 },
  { name: "Enzo Fernández", country: "Argentina", position: "MID", number: 24 },
  { name: "Giovanni Lo Celso", country: "Argentina", position: "MID", number: 16 },
  { name: "Thiago Almada", country: "Argentina", position: "MID", number: 18 },
  { name: "Lionel Messi", country: "Argentina", position: "FWD", number: 10 },
  { name: "Julián Álvarez", country: "Argentina", position: "FWD", number: 9 },
  { name: "Lautaro Martínez", country: "Argentina", position: "FWD", number: 22 },
  { name: "Paulo Dybala", country: "Argentina", position: "FWD", number: 21 },
  { name: "Alejandro Garnacho", country: "Argentina", position: "FWD", number: 11 },
  { name: "Nicolás González", country: "Argentina", position: "FWD", number: 17 },

  // ── AUSTRALIA ──
  { name: "Mat Ryan", country: "Australia", position: "GK", number: 1 },
  { name: "Andrew Redmayne", country: "Australia", position: "GK", number: 18 },
  { name: "Danny Vukovic", country: "Australia", position: "GK", number: 23 },
  { name: "Bailey Wright", country: "Australia", position: "DEF", number: 5 },
  { name: "Harry Souttar", country: "Australia", position: "DEF", number: 3 },
  { name: "Milos Degenek", country: "Australia", position: "DEF", number: 2 },
  { name: "Joel King", country: "Australia", position: "DEF", number: 20 },
  { name: "Aziz Behich", country: "Australia", position: "DEF", number: 4 },
  { name: "Nathaniel Atkinson", country: "Australia", position: "DEF", number: 15 },
  { name: "Jackson Irvine", country: "Australia", position: "MID", number: 8 },
  { name: "Riley McGree", country: "Australia", position: "MID", number: 7 },
  { name: "Aaron Mooy", country: "Australia", position: "MID", number: 13 },
  { name: "Ajdin Hrustic", country: "Australia", position: "MID", number: 10 },
  { name: "Cameron Devlin", country: "Australia", position: "MID", number: 19 },
  { name: "Mathew Leckie", country: "Australia", position: "FWD", number: 9 },
  { name: "Mitchell Duke", country: "Australia", position: "FWD", number: 11 },
  { name: "Martin Boyle", country: "Australia", position: "FWD", number: 14 },
  { name: "Craig Goodwin", country: "Australia", position: "FWD", number: 16 },
  { name: "Jamie Maclaren", country: "Australia", position: "FWD", number: 17 },
  { name: "Awer Mabil", country: "Australia", position: "FWD", number: 21 },

  // ── AUSTRIA ──
  { name: "Patrick Pentz", country: "Austria", position: "GK", number: 1 },
  { name: "Heinz Lindner", country: "Austria", position: "GK", number: 12 },
  { name: "Pavao Pervan", country: "Austria", position: "GK", number: 23 },
  { name: "Stefan Posch", country: "Austria", position: "DEF", number: 5 },
  { name: "Philipp Lienhart", country: "Austria", position: "DEF", number: 4 },
  { name: "Kevin Danso", country: "Austria", position: "DEF", number: 3 },
  { name: "Maximilian Wöber", country: "Austria", position: "DEF", number: 6 },
  { name: "David Alaba", country: "Austria", position: "DEF", number: 8 },
  { name: "Alexander Prass", country: "Austria", position: "DEF", number: 2 },
  { name: "Konrad Laimer", country: "Austria", position: "MID", number: 7 },
  { name: "Marcel Sabitzer", country: "Austria", position: "MID", number: 9 },
  { name: "Florian Grillitsch", country: "Austria", position: "MID", number: 16 },
  { name: "Xaver Schlager", country: "Austria", position: "MID", number: 18 },
  { name: "Christoph Baumgartner", country: "Austria", position: "MID", number: 14 },
  { name: "Nicolas Seiwald", country: "Austria", position: "MID", number: 17 },
  { name: "Michael Gregoritsch", country: "Austria", position: "FWD", number: 11 },
  { name: "Marko Arnautović", country: "Austria", position: "FWD", number: 10 },
  { name: "Sasa Kalajdzic", country: "Austria", position: "FWD", number: 19 },
  { name: "Patrick Wimmer", country: "Austria", position: "FWD", number: 20 },

  // ── BELGIUM ──
  { name: "Koen Casteels", country: "Belgium", position: "GK", number: 1 },
  { name: "Simon Mignolet", country: "Belgium", position: "GK", number: 12 },
  { name: "Matz Sels", country: "Belgium", position: "GK", number: 23 },
  { name: "Thomas Meunier", country: "Belgium", position: "DEF", number: 2 },
  { name: "Toby Alderweireld", country: "Belgium", position: "DEF", number: 4 },
  { name: "Jan Vertonghen", country: "Belgium", position: "DEF", number: 5 },
  { name: "Wout Faes", country: "Belgium", position: "DEF", number: 3 },
  { name: "Arthur Theate", country: "Belgium", position: "DEF", number: 22 },
  { name: "Timothy Castagne", country: "Belgium", position: "DEF", number: 15 },
  { name: "Kevin De Bruyne", country: "Belgium", position: "MID", number: 7 },
  { name: "Youri Tielemans", country: "Belgium", position: "MID", number: 8 },
  { name: "Amadou Onana", country: "Belgium", position: "MID", number: 6 },
  { name: "Axel Witsel", country: "Belgium", position: "MID", number: 16 },
  { name: "Leandro Trossard", country: "Belgium", position: "FWD", number: 11 },
  { name: "Dodi Lukébakio", country: "Belgium", position: "FWD", number: 17 },
  { name: "Romelu Lukaku", country: "Belgium", position: "FWD", number: 9 },
  { name: "Lois Openda", country: "Belgium", position: "FWD", number: 20 },
  { name: "Yannick Carrasco", country: "Belgium", position: "FWD", number: 10 },
  { name: "Johan Bakayoko", country: "Belgium", position: "FWD", number: 19 },
  { name: "Charles De Ketelaere", country: "Belgium", position: "FWD", number: 14 },

  // ── BOSNIA-HERZEGOVINA ──
  { name: "Ibrahim Šehić", country: "Bosnia-Herzegovina", position: "GK", number: 1 },
  { name: "Nikola Vasilj", country: "Bosnia-Herzegovina", position: "GK", number: 12 },
  { name: "Sead Kolašinac", country: "Bosnia-Herzegovina", position: "DEF", number: 5 },
  { name: "Toni Šunjić", country: "Bosnia-Herzegovina", position: "DEF", number: 4 },
  { name: "Ermin Bičakčić", country: "Bosnia-Herzegovina", position: "DEF", number: 3 },
  { name: "Ognjen Vranješ", country: "Bosnia-Herzegovina", position: "DEF", number: 6 },
  { name: "Denis Huseinbašić", country: "Bosnia-Herzegovina", position: "MID", number: 8 },
  { name: "Miralem Pjanić", country: "Bosnia-Herzegovina", position: "MID", number: 10 },
  { name: "Haris Duljevic", country: "Bosnia-Herzegovina", position: "MID", number: 16 },
  { name: "Miroslav Stevanović", country: "Bosnia-Herzegovina", position: "MID", number: 11 },
  { name: "Edin Džeko", country: "Bosnia-Herzegovina", position: "FWD", number: 9 },
  { name: "Muamer Tankovic", country: "Bosnia-Herzegovina", position: "FWD", number: 17 },
  { name: "Nedim Bajrami", country: "Bosnia-Herzegovina", position: "MID", number: 14 },
  { name: "Amer Gojak", country: "Bosnia-Herzegovina", position: "MID", number: 15 },
  { name: "Ermedin Demirović", country: "Bosnia-Herzegovina", position: "FWD", number: 20 },

  // ── BRAZIL ──
  { name: "Alisson Becker", country: "Brazil", position: "GK", number: 1 },
  { name: "Ederson", country: "Brazil", position: "GK", number: 23 },
  { name: "Weverton", country: "Brazil", position: "GK", number: 12 },
  { name: "Danilo", country: "Brazil", position: "DEF", number: 13 },
  { name: "Éder Militão", country: "Brazil", position: "DEF", number: 3 },
  { name: "Marquinhos", country: "Brazil", position: "DEF", number: 4 },
  { name: "Gabriel Magalhães", country: "Brazil", position: "DEF", number: 5 },
  { name: "Wendell", country: "Brazil", position: "DEF", number: 6 },
  { name: "Bremer", country: "Brazil", position: "DEF", number: 14 },
  { name: "Alex Sandro", country: "Brazil", position: "DEF", number: 2 },
  { name: "Lucas Paquetá", country: "Brazil", position: "MID", number: 10 },
  { name: "Casemiro", country: "Brazil", position: "MID", number: 8 },
  { name: "Bruno Guimarães", country: "Brazil", position: "MID", number: 18 },
  { name: "Gerson", country: "Brazil", position: "MID", number: 17 },
  { name: "Andreas Pereira", country: "Brazil", position: "MID", number: 20 },
  { name: "Vinícius Jr", country: "Brazil", position: "FWD", number: 7 },
  { name: "Rodrygo", country: "Brazil", position: "FWD", number: 11 },
  { name: "Raphinha", country: "Brazil", position: "FWD", number: 9 },
  { name: "Gabriel Jesus", country: "Brazil", position: "FWD", number: 19 },
  { name: "Richarlison", country: "Brazil", position: "FWD", number: 21 },
  { name: "Gabriel Martinelli", country: "Brazil", position: "FWD", number: 26 },
  { name: "Endrick", country: "Brazil", position: "FWD", number: 16 },

  // ── CANADA ──
  { name: "Maxime Crépeau", country: "Canada", position: "GK", number: 1 },
  { name: "Milan Borjan", country: "Canada", position: "GK", number: 18 },
  { name: "James Pantemis", country: "Canada", position: "GK", number: 23 },
  { name: "Kamal Miller", country: "Canada", position: "DEF", number: 5 },
  { name: "Alistair Johnston", country: "Canada", position: "DEF", number: 2 },
  { name: "Sam Adekugbe", country: "Canada", position: "DEF", number: 3 },
  { name: "Steven Vitória", country: "Canada", position: "DEF", number: 6 },
  { name: "Richie Laryea", country: "Canada", position: "DEF", number: 22 },
  { name: "Derek Cornelius", country: "Canada", position: "DEF", number: 4 },
  { name: "Jonathan Osorio", country: "Canada", position: "MID", number: 8 },
  { name: "Stephen Eustáquio", country: "Canada", position: "MID", number: 7 },
  { name: "Mark-Anthony Kaye", country: "Canada", position: "MID", number: 14 },
  { name: "Samuel Piette", country: "Canada", position: "MID", number: 16 },
  { name: "Tajon Buchanan", country: "Canada", position: "FWD", number: 11 },
  { name: "Alphonso Davies", country: "Canada", position: "FWD", number: 10 },
  { name: "Cyle Larin", country: "Canada", position: "FWD", number: 9 },
  { name: "Jonathan David", country: "Canada", position: "FWD", number: 20 },
  { name: "Liam Millar", country: "Canada", position: "FWD", number: 19 },
  { name: "Ismaël Koné", country: "Canada", position: "MID", number: 15 },

  // ── CAPE VERDE ──
  { name: "Vozinha", country: "Cape Verde", position: "GK", number: 1 },
  { name: "Fábio Fernandes", country: "Cape Verde", position: "GK", number: 23 },
  { name: "Roberto Lopes", country: "Cape Verde", position: "DEF", number: 5 },
  { name: "Stopira", country: "Cape Verde", position: "DEF", number: 4 },
  { name: "Dylan Tavares", country: "Cape Verde", position: "DEF", number: 3 },
  { name: "Gilson Benchimol", country: "Cape Verde", position: "DEF", number: 2 },
  { name: "Florentino Luís", country: "Cape Verde", position: "MID", number: 6 },
  { name: "Jamiro Monteiro", country: "Cape Verde", position: "MID", number: 8 },
  { name: "Júnior Andrade", country: "Cape Verde", position: "MID", number: 10 },
  { name: "Ryan Mendes", country: "Cape Verde", position: "FWD", number: 7 },
  { name: "Garry Rodrigues", country: "Cape Verde", position: "FWD", number: 11 },
  { name: "Willy Semedo", country: "Cape Verde", position: "FWD", number: 9 },
  { name: "Diney", country: "Cape Verde", position: "FWD", number: 17 },

  // ── COLOMBIA ──
  { name: "Camilo Vargas", country: "Colombia", position: "GK", number: 1 },
  { name: "David Ospina", country: "Colombia", position: "GK", number: 22 },
  { name: "Aldair Quintana", country: "Colombia", position: "GK", number: 23 },
  { name: "Dávinson Sánchez", country: "Colombia", position: "DEF", number: 5 },
  { name: "Yerry Mina", country: "Colombia", position: "DEF", number: 13 },
  { name: "Johan Mojica", country: "Colombia", position: "DEF", number: 3 },
  { name: "Daniel Muñoz", country: "Colombia", position: "DEF", number: 2 },
  { name: "Santiago Arias", country: "Colombia", position: "DEF", number: 16 },
  { name: "Carlos Cuesta", country: "Colombia", position: "DEF", number: 4 },
  { name: "Jefferson Lerma", country: "Colombia", position: "MID", number: 6 },
  { name: "Wilmar Barrios", country: "Colombia", position: "MID", number: 8 },
  { name: "Richard Ríos", country: "Colombia", position: "MID", number: 20 },
  { name: "James Rodríguez", country: "Colombia", position: "MID", number: 10 },
  { name: "Mateus Uribe", country: "Colombia", position: "MID", number: 15 },
  { name: "Juan Cuadrado", country: "Colombia", position: "MID", number: 11 },
  { name: "Luis Díaz", country: "Colombia", position: "FWD", number: 7 },
  { name: "Rafael Santos Borré", country: "Colombia", position: "FWD", number: 19 },
  { name: "Jhon Durán", country: "Colombia", position: "FWD", number: 9 },
  { name: "Cucho Hernández", country: "Colombia", position: "FWD", number: 14 },
  { name: "Jhon Arias", country: "Colombia", position: "FWD", number: 17 },

  // ── CROATIA ──
  { name: "Dominik Livaković", country: "Croatia", position: "GK", number: 1 },
  { name: "Ivica Ivušić", country: "Croatia", position: "GK", number: 23 },
  { name: "Ivo Grbić", country: "Croatia", position: "GK", number: 12 },
  { name: "Josip Šutalo", country: "Croatia", position: "DEF", number: 2 },
  { name: "Joško Gvardiol", country: "Croatia", position: "DEF", number: 3 },
  { name: "Duje Ćaleta-Car", country: "Croatia", position: "DEF", number: 6 },
  { name: "Borna Sosa", country: "Croatia", position: "DEF", number: 22 },
  { name: "Šime Vrsaljko", country: "Croatia", position: "DEF", number: 19 },
  { name: "Martin Erlić", country: "Croatia", position: "DEF", number: 5 },
  { name: "Luka Modrić", country: "Croatia", position: "MID", number: 10 },
  { name: "Marcelo Brozović", country: "Croatia", position: "MID", number: 8 },
  { name: "Mateo Kovačić", country: "Croatia", position: "MID", number: 11 },
  { name: "Mario Pašalić", country: "Croatia", position: "MID", number: 9 },
  { name: "Lovro Majer", country: "Croatia", position: "MID", number: 7 },
  { name: "Nikola Vlašić", country: "Croatia", position: "MID", number: 13 },
  { name: "Ivan Perišić", country: "Croatia", position: "FWD", number: 4 },
  { name: "Andrej Kramarić", country: "Croatia", position: "FWD", number: 16 },
  { name: "Bruno Petković", country: "Croatia", position: "FWD", number: 14 },
  { name: "Marko Livaja", country: "Croatia", position: "FWD", number: 17 },

  // ── CURAÇAO ──
  { name: "Eloy Room", country: "Curaçao", position: "GK", number: 1 },
  { name: "Cuco Martina", country: "Curaçao", position: "DEF", number: 2 },
  { name: "Juriën Gaari", country: "Curaçao", position: "DEF", number: 5 },
  { name: "Ethan Lachman", country: "Curaçao", position: "DEF", number: 3 },
  { name: "Vurnon Anita", country: "Curaçao", position: "MID", number: 6 },
  { name: "Leandro Bacuna", country: "Curaçao", position: "MID", number: 8 },
  { name: "Gevaro Nepomuceno", country: "Curaçao", position: "MID", number: 10 },
  { name: "Giliano Wijnaldum", country: "Curaçao", position: "FWD", number: 9 },
  { name: "Ragnar Oratmangoen", country: "Curaçao", position: "FWD", number: 7 },
  { name: "Ryan Babel", country: "Curaçao", position: "FWD", number: 11 },
  { name: "Quiñero Croes", country: "Curaçao", position: "FWD", number: 17 },

  // ── CZECHIA ──
  { name: "Jiří Pavlenka", country: "Czechia", position: "GK", number: 1 },
  { name: "Tomáš Vaclík", country: "Czechia", position: "GK", number: 12 },
  { name: "Aleš Mandous", country: "Czechia", position: "GK", number: 23 },
  { name: "Vladimír Coufal", country: "Czechia", position: "DEF", number: 2 },
  { name: "Tomáš Kalas", country: "Czechia", position: "DEF", number: 4 },
  { name: "Jan Bořil", country: "Czechia", position: "DEF", number: 3 },
  { name: "Ondřej Čelůstka", country: "Czechia", position: "DEF", number: 5 },
  { name: "Ladislav Krejčí", country: "Czechia", position: "DEF", number: 6 },
  { name: "Tomáš Souček", country: "Czechia", position: "MID", number: 8 },
  { name: "Alex Král", country: "Czechia", position: "MID", number: 18 },
  { name: "Lukáš Provod", country: "Czechia", position: "MID", number: 10 },
  { name: "Jakub Jankto", country: "Czechia", position: "MID", number: 15 },
  { name: "Lukáš Haraslín", country: "Czechia", position: "MID", number: 19 },
  { name: "Patrik Schick", country: "Czechia", position: "FWD", number: 9 },
  { name: "Adam Hložek", country: "Czechia", position: "FWD", number: 11 },
  { name: "Tomáš Chorý", country: "Czechia", position: "FWD", number: 20 },
  { name: "Mojmír Chytil", country: "Czechia", position: "FWD", number: 14 },
  { name: "Jan Kuchta", country: "Czechia", position: "FWD", number: 17 },

  // ── DR CONGO ──
  { name: "Joël Kiassumbua", country: "DR Congo", position: "GK", number: 1 },
  { name: "Lionel Mpasi", country: "DR Congo", position: "DEF", number: 2 },
  { name: "Chancel Mbemba", country: "DR Congo", position: "DEF", number: 4 },
  { name: "Pierre Kalulu", country: "DR Congo", position: "DEF", number: 5 },
  { name: "Arthur Masuaku", country: "DR Congo", position: "DEF", number: 3 },
  { name: "Samuel Moutoussamy", country: "DR Congo", position: "MID", number: 8 },
  { name: "Yoane Wissa", country: "DR Congo", position: "FWD", number: 7 },
  { name: "Cédric Bakambu", country: "DR Congo", position: "FWD", number: 9 },
  { name: "Théo Bongonda", country: "DR Congo", position: "FWD", number: 11 },
  { name: "Yannick Bolasie", country: "DR Congo", position: "FWD", number: 17 },
  { name: "Silas Mvumpa", country: "DR Congo", position: "FWD", number: 10 },
  { name: "Paul-José Mpoku", country: "DR Congo", position: "MID", number: 14 },

  // ── ECUADOR ──
  { name: "Hernán Galíndez", country: "Ecuador", position: "GK", number: 1 },
  { name: "Moisés Ramírez", country: "Ecuador", position: "GK", number: 12 },
  { name: "Alexander Domínguez", country: "Ecuador", position: "GK", number: 23 },
  { name: "Piero Hincapié", country: "Ecuador", position: "DEF", number: 3 },
  { name: "Félix Torres", country: "Ecuador", position: "DEF", number: 5 },
  { name: "Robert Arboleda", country: "Ecuador", position: "DEF", number: 4 },
  { name: "Pervis Estupiñán", country: "Ecuador", position: "DEF", number: 2 },
  { name: "Angelo Preciado", country: "Ecuador", position: "DEF", number: 22 },
  { name: "Diego Palacios", country: "Ecuador", position: "DEF", number: 17 },
  { name: "Moisés Caicedo", country: "Ecuador", position: "MID", number: 6 },
  { name: "Carlos Gruezo", country: "Ecuador", position: "MID", number: 8 },
  { name: "José Cifuentes", country: "Ecuador", position: "MID", number: 20 },
  { name: "Jeremy Sarmiento", country: "Ecuador", position: "MID", number: 16 },
  { name: "Ángel Mena", country: "Ecuador", position: "FWD", number: 11 },
  { name: "Gonzalo Plata", country: "Ecuador", position: "FWD", number: 7 },
  { name: "Enner Valencia", country: "Ecuador", position: "FWD", number: 13 },
  { name: "Michael Estrada", country: "Ecuador", position: "FWD", number: 9 },
  { name: "Kevin Rodríguez", country: "Ecuador", position: "FWD", number: 19 },

  // ── EGYPT ──
  { name: "Mohamed El-Shennawy", country: "Egypt", position: "GK", number: 1 },
  { name: "Ahmed El-Shennawy", country: "Egypt", position: "GK", number: 23 },
  { name: "Ahmed Hegazi", country: "Egypt", position: "DEF", number: 5 },
  { name: "Omar Kamal", country: "Egypt", position: "DEF", number: 3 },
  { name: "Baher El-Mohamady", country: "Egypt", position: "DEF", number: 2 },
  { name: "Mohamed Abdel-Shafy", country: "Egypt", position: "DEF", number: 6 },
  { name: "Trezeguet", country: "Egypt", position: "MID", number: 11 },
  { name: "Amr El-Sulaya", country: "Egypt", position: "MID", number: 8 },
  { name: "Tarek Hamed", country: "Egypt", position: "MID", number: 17 },
  { name: "Mohamed Elneny", country: "Egypt", position: "MID", number: 14 },
  { name: "Emam Ashour", country: "Egypt", position: "MID", number: 10 },
  { name: "Mohamed Salah", country: "Egypt", position: "FWD", number: 10 },
  { name: "Mostafa Mohamed", country: "Egypt", position: "FWD", number: 9 },
  { name: "Marwan Hamdy", country: "Egypt", position: "FWD", number: 19 },
  { name: "Omar Marmoush", country: "Egypt", position: "FWD", number: 20 },
  { name: "Zizo", country: "Egypt", position: "FWD", number: 7 },

  // ── ENGLAND ──
  { name: "Jordan Pickford", country: "England", position: "GK", number: 1 },
  { name: "Aaron Ramsdale", country: "England", position: "GK", number: 12 },
  { name: "Nick Pope", country: "England", position: "GK", number: 23 },
  { name: "Trent Alexander-Arnold", country: "England", position: "DEF", number: 2 },
  { name: "Kieran Trippier", country: "England", position: "DEF", number: 22 },
  { name: "John Stones", country: "England", position: "DEF", number: 5 },
  { name: "Harry Maguire", country: "England", position: "DEF", number: 6 },
  { name: "Luke Shaw", country: "England", position: "DEF", number: 3 },
  { name: "Marc Guéhi", country: "England", position: "DEF", number: 4 },
  { name: "Conor Gallagher", country: "England", position: "MID", number: 16 },
  { name: "Declan Rice", country: "England", position: "MID", number: 4 },
  { name: "Jude Bellingham", country: "England", position: "MID", number: 10 },
  { name: "Kobbie Mainoo", country: "England", position: "MID", number: 26 },
  { name: "Phil Foden", country: "England", position: "MID", number: 11 },
  { name: "James Maddison", country: "England", position: "MID", number: 14 },
  { name: "Bukayo Saka", country: "England", position: "FWD", number: 7 },
  { name: "Harry Kane", country: "England", position: "FWD", number: 9 },
  { name: "Marcus Rashford", country: "England", position: "FWD", number: 11 },
  { name: "Ollie Watkins", country: "England", position: "FWD", number: 19 },
  { name: "Cole Palmer", country: "England", position: "FWD", number: 20 },
  { name: "Anthony Gordon", country: "England", position: "FWD", number: 17 },

  // ── FRANCE ──
  { name: "Mike Maignan", country: "France", position: "GK", number: 16 },
  { name: "Alphonse Areola", country: "France", position: "GK", number: 1 },
  { name: "Brice Samba", country: "France", position: "GK", number: 23 },
  { name: "Jules Koundé", country: "France", position: "DEF", number: 5 },
  { name: "Dayot Upamecano", country: "France", position: "DEF", number: 4 },
  { name: "William Saliba", country: "France", position: "DEF", number: 17 },
  { name: "Ibrahima Konaté", country: "France", position: "DEF", number: 3 },
  { name: "Theo Hernández", country: "France", position: "DEF", number: 22 },
  { name: "Benjamin Pavard", country: "France", position: "DEF", number: 2 },
  { name: "Eduardo Camavinga", country: "France", position: "MID", number: 8 },
  { name: "Aurélien Tchouaméni", country: "France", position: "MID", number: 8 },
  { name: "Antoine Griezmann", country: "France", position: "MID", number: 7 },
  { name: "Adrien Rabiot", country: "France", position: "MID", number: 14 },
  { name: "Warren Zaïre-Emery", country: "France", position: "MID", number: 20 },
  { name: "Kylian Mbappé", country: "France", position: "FWD", number: 10 },
  { name: "Ousmane Dembélé", country: "France", position: "FWD", number: 11 },
  { name: "Marcus Thuram", country: "France", position: "FWD", number: 9 },
  { name: "Randal Kolo Muani", country: "France", position: "FWD", number: 13 },
  { name: "Bradley Barcola", country: "France", position: "FWD", number: 21 },
  { name: "Kingsley Coman", country: "France", position: "FWD", number: 12 },

  // ── GERMANY ──
  { name: "Manuel Neuer", country: "Germany", position: "GK", number: 1 },
  { name: "Marc-André ter Stegen", country: "Germany", position: "GK", number: 12 },
  { name: "Oliver Baumann", country: "Germany", position: "GK", number: 23 },
  { name: "Joshua Kimmich", country: "Germany", position: "DEF", number: 6 },
  { name: "Antonio Rüdiger", country: "Germany", position: "DEF", number: 2 },
  { name: "Niklas Süle", country: "Germany", position: "DEF", number: 5 },
  { name: "Jonathan Tah", country: "Germany", position: "DEF", number: 4 },
  { name: "David Raum", country: "Germany", position: "DEF", number: 3 },
  { name: "Nico Schlotterbeck", country: "Germany", position: "DEF", number: 15 },
  { name: "Waldemar Anton", country: "Germany", position: "DEF", number: 16 },
  { name: "Ilkay Gündogan", country: "Germany", position: "MID", number: 8 },
  { name: "Toni Kroos", country: "Germany", position: "MID", number: 8 },
  { name: "Florian Wirtz", country: "Germany", position: "MID", number: 10 },
  { name: "Thomas Müller", country: "Germany", position: "FWD", number: 13 },
  { name: "Jamal Musiala", country: "Germany", position: "FWD", number: 14 },
  { name: "Kai Havertz", country: "Germany", position: "FWD", number: 7 },
  { name: "Leroy Sané", country: "Germany", position: "FWD", number: 19 },
  { name: "Serge Gnabry", country: "Germany", position: "FWD", number: 20 },
  { name: "Niclas Füllkrug", country: "Germany", position: "FWD", number: 9 },
  { name: "Deniz Undav", country: "Germany", position: "FWD", number: 26 },

  // ── GHANA ──
  { name: "Lawrence Ati-Zigi", country: "Ghana", position: "GK", number: 1 },
  { name: "Joseph Wollacott", country: "Ghana", position: "GK", number: 23 },
  { name: "Daniel Amartey", country: "Ghana", position: "DEF", number: 5 },
  { name: "Alexander Djiku", country: "Ghana", position: "DEF", number: 4 },
  { name: "Tariq Lamptey", country: "Ghana", position: "DEF", number: 2 },
  { name: "Abdul Rahman Baba", country: "Ghana", position: "DEF", number: 3 },
  { name: "Gideon Mensah", country: "Ghana", position: "DEF", number: 22 },
  { name: "Thomas Partey", country: "Ghana", position: "MID", number: 6 },
  { name: "Baba Idrissu", country: "Ghana", position: "MID", number: 8 },
  { name: "Mohammed Kudus", country: "Ghana", position: "MID", number: 10 },
  { name: "Daniel-Kofi Kyereh", country: "Ghana", position: "MID", number: 14 },
  { name: "Iñaki Williams", country: "Ghana", position: "FWD", number: 9 },
  { name: "Jordan Ayew", country: "Ghana", position: "FWD", number: 11 },
  { name: "André Ayew", country: "Ghana", position: "FWD", number: 21 },
  { name: "Antoine Semenyo", country: "Ghana", position: "FWD", number: 17 },
  { name: "Kamaldeen Sulemana", country: "Ghana", position: "FWD", number: 7 },
  { name: "Ernest Nuamah", country: "Ghana", position: "FWD", number: 19 },

  // ── HAITI ──
  { name: "Kerly Theus", country: "Haiti", position: "GK", number: 1 },
  { name: "Fetzi Romelus", country: "Haiti", position: "GK", number: 23 },
  { name: "James Léandre", country: "Haiti", position: "DEF", number: 5 },
  { name: "Mechack Jérome", country: "Haiti", position: "DEF", number: 4 },
  { name: "Jems Geffrard", country: "Haiti", position: "DEF", number: 6 },
  { name: "Frantzdy Pierrot", country: "Haiti", position: "MID", number: 8 },
  { name: "Dorilas Woodens", country: "Haiti", position: "MID", number: 10 },
  { name: "Wilde-Donald Guerrier", country: "Haiti", position: "FWD", number: 7 },
  { name: "Duckens Nazon", country: "Haiti", position: "FWD", number: 9 },
  { name: "Derrick Etienne Jr", country: "Haiti", position: "FWD", number: 11 },
  { name: "Nazon Duckens", country: "Haiti", position: "FWD", number: 17 },

  // ── IRAN ──
  { name: "Alireza Beiranvand", country: "Iran", position: "GK", number: 1 },
  { name: "Hossein Hosseini", country: "Iran", position: "GK", number: 12 },
  { name: "Payam Niazmand", country: "Iran", position: "GK", number: 23 },
  { name: "Sadegh Moharrami", country: "Iran", position: "DEF", number: 2 },
  { name: "Shoja Khalilzadeh", country: "Iran", position: "DEF", number: 5 },
  { name: "Majid Hosseini", country: "Iran", position: "DEF", number: 4 },
  { name: "Milad Mohammadi", country: "Iran", position: "DEF", number: 3 },
  { name: "Ramin Rezaeian", country: "Iran", position: "DEF", number: 17 },
  { name: "Saeid Ezatolahi", country: "Iran", position: "MID", number: 6 },
  { name: "Ahmad Noorollahi", country: "Iran", position: "MID", number: 8 },
  { name: "Mehdi Torabi", country: "Iran", position: "MID", number: 10 },
  { name: "Saman Ghoddos", country: "Iran", position: "MID", number: 14 },
  { name: "Ali Karimi", country: "Iran", position: "MID", number: 16 },
  { name: "Sardar Azmoun", country: "Iran", position: "FWD", number: 9 },
  { name: "Mehdi Taremi", country: "Iran", position: "FWD", number: 7 },
  { name: "Ali Gholizadeh", country: "Iran", position: "FWD", number: 11 },
  { name: "Allahyar Sayyadmanesh", country: "Iran", position: "FWD", number: 19 },

  // ── IRAQ ──
  { name: "Jalal Hassan", country: "Iraq", position: "GK", number: 1 },
  { name: "Mohammed Hameed", country: "Iraq", position: "GK", number: 23 },
  { name: "Ali Adnan", country: "Iraq", position: "DEF", number: 3 },
  { name: "Amjad Attwan", country: "Iraq", position: "DEF", number: 4 },
  { name: "Saad Natiq", country: "Iraq", position: "DEF", number: 2 },
  { name: "Rebin Sulaka", country: "Iraq", position: "DEF", number: 5 },
  { name: "Hussein Ali", country: "Iraq", position: "MID", number: 8 },
  { name: "Safaa Hadi", country: "Iraq", position: "MID", number: 6 },
  { name: "Bashar Resan", country: "Iraq", position: "MID", number: 10 },
  { name: "Mohanad Ali", country: "Iraq", position: "MID", number: 14 },
  { name: "Aymen Hussein", country: "Iraq", position: "FWD", number: 9 },
  { name: "Ahmed Yasin", country: "Iraq", position: "FWD", number: 7 },
  { name: "Shahin", country: "Iraq", position: "FWD", number: 11 },

  // ── IVORY COAST ──
  { name: "Yahia Fofana", country: "Ivory Coast", position: "GK", number: 1 },
  { name: "Badra Ali Sangaré", country: "Ivory Coast", position: "GK", number: 23 },
  { name: "Serge Aurier", country: "Ivory Coast", position: "DEF", number: 2 },
  { name: "Simon Deli", country: "Ivory Coast", position: "DEF", number: 4 },
  { name: "Odilon Kossounou", country: "Ivory Coast", position: "DEF", number: 3 },
  { name: "Wilfried Singo", country: "Ivory Coast", position: "DEF", number: 22 },
  { name: "Willy Boly", country: "Ivory Coast", position: "DEF", number: 5 },
  { name: "Franck Kessié", country: "Ivory Coast", position: "MID", number: 8 },
  { name: "Ibrahim Sangaré", country: "Ivory Coast", position: "MID", number: 6 },
  { name: "Jean-Philippe Gbamin", country: "Ivory Coast", position: "MID", number: 16 },
  { name: "Sébastien Haller", country: "Ivory Coast", position: "FWD", number: 9 },
  { name: "Nicolas Pépé", country: "Ivory Coast", position: "FWD", number: 19 },
  { name: "Wilfried Zaha", country: "Ivory Coast", position: "FWD", number: 11 },
  { name: "Simon Adingra", country: "Ivory Coast", position: "FWD", number: 7 },
  { name: "Oumar Diakité", country: "Ivory Coast", position: "FWD", number: 14 },
  { name: "Jonathan Bamba", country: "Ivory Coast", position: "FWD", number: 10 },

  // ── JAPAN ──
  { name: "Shuichi Gonda", country: "Japan", position: "GK", number: 1 },
  { name: "Zion Suzuki", country: "Japan", position: "GK", number: 23 },
  { name: "Kosei Tani", country: "Japan", position: "GK", number: 12 },
  { name: "Hiroki Sakai", country: "Japan", position: "DEF", number: 5 },
  { name: "Yuto Nagatomo", country: "Japan", position: "DEF", number: 3 },
  { name: "Maya Yoshida", country: "Japan", position: "DEF", number: 22 },
  { name: "Ko Itakura", country: "Japan", position: "DEF", number: 6 },
  { name: "Takehiro Tomiyasu", country: "Japan", position: "DEF", number: 2 },
  { name: "Wataru Endo", country: "Japan", position: "MID", number: 8 },
  { name: "Hidemasa Morita", country: "Japan", position: "MID", number: 16 },
  { name: "Daichi Kamada", country: "Japan", position: "MID", number: 10 },
  { name: "Ao Tanaka", country: "Japan", position: "MID", number: 15 },
  { name: "Kaoru Mitoma", country: "Japan", position: "FWD", number: 7 },
  { name: "Takumi Minamino", country: "Japan", position: "FWD", number: 9 },
  { name: "Ritsu Doan", country: "Japan", position: "FWD", number: 14 },
  { name: "Junya Ito", country: "Japan", position: "FWD", number: 11 },
  { name: "Ayase Ueda", country: "Japan", position: "FWD", number: 19 },
  { name: "Keito Nakamura", country: "Japan", position: "FWD", number: 17 },
  { name: "Daizen Maeda", country: "Japan", position: "FWD", number: 13 },

  // ── JORDAN ──
  { name: "Amer Shafi", country: "Jordan", position: "GK", number: 1 },
  { name: "Mutaz Yaseen", country: "Jordan", position: "DEF", number: 4 },
  { name: "Yazan Al Naimat", country: "Jordan", position: "DEF", number: 5 },
  { name: "Baha Faisal", country: "Jordan", position: "DEF", number: 3 },
  { name: "Musa Al Taamari", country: "Jordan", position: "MID", number: 10 },
  { name: "Mahmoud Al Mardi", country: "Jordan", position: "MID", number: 8 },
  { name: "Naser Al Rashdan", country: "Jordan", position: "MID", number: 6 },
  { name: "Mohammad Abu Zema", country: "Jordan", position: "FWD", number: 9 },
  { name: "Ahmad Harman", country: "Jordan", position: "FWD", number: 11 },
  { name: "Zaid Khreisat", country: "Jordan", position: "FWD", number: 7 },

  // ── MEXICO ──
  { name: "Guillermo Ochoa", country: "Mexico", position: "GK", number: 13 },
  { name: "Luis Malagón", country: "Mexico", position: "GK", number: 1 },
  { name: "Rodolfo Cota", country: "Mexico", position: "GK", number: 23 },
  { name: "Jorge Sánchez", country: "Mexico", position: "DEF", number: 2 },
  { name: "Kevin Álvarez", country: "Mexico", position: "DEF", number: 22 },
  { name: "Jesús Gallardo", country: "Mexico", position: "DEF", number: 3 },
  { name: "Johan Vásquez", country: "Mexico", position: "DEF", number: 5 },
  { name: "César Montes", country: "Mexico", position: "DEF", number: 4 },
  { name: "Héctor Moreno", country: "Mexico", position: "DEF", number: 15 },
  { name: "Edson Álvarez", country: "Mexico", position: "MID", number: 18 },
  { name: "Andrés Guardado", country: "Mexico", position: "MID", number: 8 },
  { name: "Carlos Rodríguez", country: "Mexico", position: "MID", number: 7 },
  { name: "Héctor Herrera", country: "Mexico", position: "MID", number: 16 },
  { name: "Orbelin Pineda", country: "Mexico", position: "MID", number: 10 },
  { name: "Luis Romo", country: "Mexico", position: "MID", number: 14 },
  { name: "Hirving Lozano", country: "Mexico", position: "FWD", number: 22 },
  { name: "Raúl Jiménez", country: "Mexico", position: "FWD", number: 9 },
  { name: "Henry Martín", country: "Mexico", position: "FWD", number: 21 },
  { name: "Santiago Giménez", country: "Mexico", position: "FWD", number: 11 },
  { name: "Uriel Antuna", country: "Mexico", position: "FWD", number: 17 },
  { name: "Roberto Alvarado", country: "Mexico", position: "FWD", number: 19 },

  // ── MOROCCO ──
  { name: "Yassine Bounou", country: "Morocco", position: "GK", number: 1 },
  { name: "Munir El Kajoui", country: "Morocco", position: "GK", number: 12 },
  { name: "Ahmed Reda Tagnaouti", country: "Morocco", position: "GK", number: 23 },
  { name: "Achraf Hakimi", country: "Morocco", position: "DEF", number: 2 },
  { name: "Nayef Aguerd", country: "Morocco", position: "DEF", number: 5 },
  { name: "Romain Saïss", country: "Morocco", position: "DEF", number: 6 },
  { name: "Jawad El Yamiq", country: "Morocco", position: "DEF", number: 4 },
  { name: "Noussair Mazraoui", country: "Morocco", position: "DEF", number: 3 },
  { name: "Adam Masina", country: "Morocco", position: "DEF", number: 22 },
  { name: "Selim Amallah", country: "Morocco", position: "MID", number: 8 },
  { name: "Azzedine Ounahi", country: "Morocco", position: "MID", number: 16 },
  { name: "Sofyan Amrabat", country: "Morocco", position: "MID", number: 4 },
  { name: "Ilias Chair", country: "Morocco", position: "MID", number: 10 },
  { name: "Bilal El Khannouss", country: "Morocco", position: "MID", number: 15 },
  { name: "Hakim Ziyech", country: "Morocco", position: "FWD", number: 7 },
  { name: "Sofiane Boufal", country: "Morocco", position: "FWD", number: 11 },
  { name: "Youssef En-Nesyri", country: "Morocco", position: "FWD", number: 19 },
  { name: "Zakaria Aboukhlal", country: "Morocco", position: "FWD", number: 14 },
  { name: "Abderrazak Hamdallah", country: "Morocco", position: "FWD", number: 9 },

  // ── NETHERLANDS ──
  { name: "Bart Verbruggen", country: "Netherlands", position: "GK", number: 1 },
  { name: "Mark Flekken", country: "Netherlands", position: "GK", number: 12 },
  { name: "Justin Bijlow", country: "Netherlands", position: "GK", number: 23 },
  { name: "Denzel Dumfries", country: "Netherlands", position: "DEF", number: 22 },
  { name: "Virgil van Dijk", country: "Netherlands", position: "DEF", number: 4 },
  { name: "Stefan de Vrij", country: "Netherlands", position: "DEF", number: 6 },
  { name: "Nathan Aké", country: "Netherlands", position: "DEF", number: 5 },
  { name: "Daley Blind", country: "Netherlands", position: "DEF", number: 17 },
  { name: "Jurriën Timber", country: "Netherlands", position: "DEF", number: 2 },
  { name: "Tijjani Reijnders", country: "Netherlands", position: "MID", number: 14 },
  { name: "Frenkie de Jong", country: "Netherlands", position: "MID", number: 21 },
  { name: "Ryan Gravenberch", country: "Netherlands", position: "MID", number: 8 },
  { name: "Marten de Roon", country: "Netherlands", position: "MID", number: 15 },
  { name: "Teun Koopmeiners", country: "Netherlands", position: "MID", number: 10 },
  { name: "Memphis Depay", country: "Netherlands", position: "FWD", number: 10 },
  { name: "Cody Gakpo", country: "Netherlands", position: "FWD", number: 11 },
  { name: "Xavi Simons", country: "Netherlands", position: "FWD", number: 7 },
  { name: "Steven Bergwijn", country: "Netherlands", position: "FWD", number: 9 },
  { name: "Brian Brobbey", country: "Netherlands", position: "FWD", number: 19 },
  { name: "Donyell Malen", country: "Netherlands", position: "FWD", number: 18 },

  // ── NEW ZEALAND ──
  { name: "Oliver Sail", country: "New Zealand", position: "GK", number: 1 },
  { name: "Stefan Marinovic", country: "New Zealand", position: "GK", number: 12 },
  { name: "Michael Boxall", country: "New Zealand", position: "DEF", number: 5 },
  { name: "Winston Reid", country: "New Zealand", position: "DEF", number: 4 },
  { name: "Tommy Smith", country: "New Zealand", position: "DEF", number: 2 },
  { name: "Liberato Cacace", country: "New Zealand", position: "DEF", number: 3 },
  { name: "Clayton Lewis", country: "New Zealand", position: "MID", number: 8 },
  { name: "Regan Donelon", country: "New Zealand", position: "MID", number: 6 },
  { name: "Sarpreet Singh", country: "New Zealand", position: "MID", number: 10 },
  { name: "Andre De Jong", country: "New Zealand", position: "MID", number: 14 },
  { name: "Chris Wood", country: "New Zealand", position: "FWD", number: 9 },
  { name: "Kosta Barbarouses", country: "New Zealand", position: "FWD", number: 11 },
  { name: "Callan Elliott", country: "New Zealand", position: "FWD", number: 17 },
  { name: "Matthew Garbett", country: "New Zealand", position: "MID", number: 16 },

  // ── NORWAY ──
  { name: "Ørjan Nyland", country: "Norway", position: "GK", number: 1 },
  { name: "Håkon Opdal", country: "Norway", position: "GK", number: 12 },
  { name: "Stefan Strandberg", country: "Norway", position: "DEF", number: 5 },
  { name: "Leo Østigård", country: "Norway", position: "DEF", number: 4 },
  { name: "Andreas Hanche-Olsen", country: "Norway", position: "DEF", number: 6 },
  { name: "Omar Elabdellaoui", country: "Norway", position: "DEF", number: 2 },
  { name: "Birger Meling", country: "Norway", position: "DEF", number: 3 },
  { name: "Martin Ødegaard", country: "Norway", position: "MID", number: 10 },
  { name: "Sander Berge", country: "Norway", position: "MID", number: 8 },
  { name: "Fredrik Aursnes", country: "Norway", position: "MID", number: 6 },
  { name: "Mats Møller Dæhli", country: "Norway", position: "MID", number: 14 },
  { name: "Kristian Thorstvedt", country: "Norway", position: "MID", number: 20 },
  { name: "Erling Haaland", country: "Norway", position: "FWD", number: 9 },
  { name: "Alexander Sørloth", country: "Norway", position: "FWD", number: 11 },
  { name: "Mohamed Elyounoussi", country: "Norway", position: "FWD", number: 7 },
  { name: "Ola Solbakken", country: "Norway", position: "FWD", number: 17 },
  { name: "Antonio Nusa", country: "Norway", position: "FWD", number: 19 },

  // ── PANAMA ──
  { name: "Luis Mejía", country: "Panama", position: "GK", number: 1 },
  { name: "Jaime Penedo", country: "Panama", position: "GK", number: 18 },
  { name: "Fidel Escobar", country: "Panama", position: "DEF", number: 3 },
  { name: "Eric Davis", country: "Panama", position: "DEF", number: 5 },
  { name: "Roderick Miller", country: "Panama", position: "DEF", number: 4 },
  { name: "Harold Cummings", country: "Panama", position: "DEF", number: 2 },
  { name: "Michael Murillo", country: "Panama", position: "DEF", number: 22 },
  { name: "Andrés Andrade", country: "Panama", position: "MID", number: 8 },
  { name: "Adalberto Carrasquilla", country: "Panama", position: "MID", number: 10 },
  { name: "Aníbal Godoy", country: "Panama", position: "MID", number: 6 },
  { name: "Alberto Quintero", country: "Panama", position: "MID", number: 14 },
  { name: "Édgar Bárcenas", country: "Panama", position: "FWD", number: 7 },
  { name: "Cecilio Waterman", country: "Panama", position: "FWD", number: 11 },
  { name: "Rolando Blackburn", country: "Panama", position: "FWD", number: 9 },
  { name: "Ismael Díaz", country: "Panama", position: "FWD", number: 19 },

  // ── PARAGUAY ──
  { name: "Antony Silva", country: "Paraguay", position: "GK", number: 1 },
  { name: "Alfredo Aguilar", country: "Paraguay", position: "GK", number: 23 },
  { name: "Gustavo Gómez", country: "Paraguay", position: "DEF", number: 3 },
  { name: "Fabián Balbuena", country: "Paraguay", position: "DEF", number: 4 },
  { name: "Omar Alderete", country: "Paraguay", position: "DEF", number: 5 },
  { name: "Blas Riveros", country: "Paraguay", position: "DEF", number: 2 },
  { name: "Robert Rojas", country: "Paraguay", position: "DEF", number: 6 },
  { name: "Richard Sánchez", country: "Paraguay", position: "MID", number: 8 },
  { name: "Mathías Villasanti", country: "Paraguay", position: "MID", number: 16 },
  { name: "Andrés Cubas", country: "Paraguay", position: "MID", number: 14 },
  { name: "Miguel Almirón", country: "Paraguay", position: "MID", number: 10 },
  { name: "Alejandro Romero Gamarra", country: "Paraguay", position: "MID", number: 7 },
  { name: "Carlos González", country: "Paraguay", position: "FWD", number: 9 },
  { name: "Antonio Sanabria", country: "Paraguay", position: "FWD", number: 19 },
  { name: "Ángel Romero", country: "Paraguay", position: "FWD", number: 11 },
  { name: "Julio Enciso", country: "Paraguay", position: "FWD", number: 17 },

  // ── PORTUGAL ──
  { name: "Diogo Costa", country: "Portugal", position: "GK", number: 1 },
  { name: "Rui Patrício", country: "Portugal", position: "GK", number: 12 },
  { name: "José Sá", country: "Portugal", position: "GK", number: 23 },
  { name: "Nuno Mendes", country: "Portugal", position: "DEF", number: 19 },
  { name: "Rúben Dias", country: "Portugal", position: "DEF", number: 4 },
  { name: "Danilo Pereira", country: "Portugal", position: "DEF", number: 6 },
  { name: "João Cancelo", country: "Portugal", position: "DEF", number: 20 },
  { name: "Gonçalo Inácio", country: "Portugal", position: "DEF", number: 3 },
  { name: "Diogo Dalot", country: "Portugal", position: "DEF", number: 2 },
  { name: "António Silva", country: "Portugal", position: "DEF", number: 5 },
  { name: "Vitinha", country: "Portugal", position: "MID", number: 16 },
  { name: "Bruno Fernandes", country: "Portugal", position: "MID", number: 8 },
  { name: "João Palhinha", country: "Portugal", position: "MID", number: 26 },
  { name: "Rúben Neves", country: "Portugal", position: "MID", number: 15 },
  { name: "Bernardo Silva", country: "Portugal", position: "MID", number: 10 },
  { name: "Cristiano Ronaldo", country: "Portugal", position: "FWD", number: 7 },
  { name: "Rafael Leão", country: "Portugal", position: "FWD", number: 11 },
  { name: "João Félix", country: "Portugal", position: "FWD", number: 21 },
  { name: "Gonçalo Ramos", country: "Portugal", position: "FWD", number: 9 },
  { name: "Diogo Jota", country: "Portugal", position: "FWD", number: 17 },
  { name: "Pedro Neto", country: "Portugal", position: "FWD", number: 14 },

  // ── QATAR ──
  { name: "Meshaal Barsham", country: "Qatar", position: "GK", number: 1 },
  { name: "Saad Al Sheeb", country: "Qatar", position: "GK", number: 21 },
  { name: "Pedro Miguel", country: "Qatar", position: "DEF", number: 5 },
  { name: "Bassam Al-Rawi", country: "Qatar", position: "DEF", number: 4 },
  { name: "Abdelkarim Hassan", country: "Qatar", position: "DEF", number: 3 },
  { name: "Tarek Salman", country: "Qatar", position: "DEF", number: 2 },
  { name: "Musab Khoder", country: "Qatar", position: "DEF", number: 6 },
  { name: "Karim Boudiaf", country: "Qatar", position: "MID", number: 8 },
  { name: "Homam Ahmed", country: "Qatar", position: "MID", number: 16 },
  { name: "Abdel Aziz Hatem", country: "Qatar", position: "MID", number: 10 },
  { name: "Assim Madibo", country: "Qatar", position: "MID", number: 14 },
  { name: "Akram Afif", country: "Qatar", position: "FWD", number: 11 },
  { name: "Almoez Ali", country: "Qatar", position: "FWD", number: 9 },
  { name: "Mohammed Muntari", country: "Qatar", position: "FWD", number: 7 },
  { name: "Ismaeel Mohammad", country: "Qatar", position: "FWD", number: 17 },

  // ── SAUDI ARABIA ──
  { name: "Mohammed Al-Owais", country: "Saudi Arabia", position: "GK", number: 1 },
  { name: "Fawaz Al-Qarni", country: "Saudi Arabia", position: "GK", number: 21 },
  { name: "Saud Abdulhamid", country: "Saudi Arabia", position: "DEF", number: 2 },
  { name: "Ali Al-Bulayhi", country: "Saudi Arabia", position: "DEF", number: 13 },
  { name: "Abdulelah Al-Amri", country: "Saudi Arabia", position: "DEF", number: 5 },
  { name: "Hassan Tambakti", country: "Saudi Arabia", position: "DEF", number: 4 },
  { name: "Mohammed Al-Buraik", country: "Saudi Arabia", position: "DEF", number: 3 },
  { name: "Salman Al-Faraj", country: "Saudi Arabia", position: "MID", number: 7 },
  { name: "Mohammed Kanno", country: "Saudi Arabia", position: "MID", number: 8 },
  { name: "Sami Al-Najei", country: "Saudi Arabia", position: "MID", number: 10 },
  { name: "Riyadh Sharahili", country: "Saudi Arabia", position: "MID", number: 17 },
  { name: "Firas Al-Buraikan", country: "Saudi Arabia", position: "FWD", number: 19 },
  { name: "Saleh Al-Shehri", country: "Saudi Arabia", position: "FWD", number: 9 },
  { name: "Salem Al-Dawsari", country: "Saudi Arabia", position: "FWD", number: 10 },
  { name: "Hattan Bahbir", country: "Saudi Arabia", position: "FWD", number: 11 },

  // ── SCOTLAND ──
  { name: "Craig Gordon", country: "Scotland", position: "GK", number: 1 },
  { name: "Zander Clark", country: "Scotland", position: "GK", number: 12 },
  { name: "Liam Kelly", country: "Scotland", position: "GK", number: 23 },
  { name: "Jack Hendry", country: "Scotland", position: "DEF", number: 5 },
  { name: "Kieran Tierney", country: "Scotland", position: "DEF", number: 3 },
  { name: "Grant Hanley", country: "Scotland", position: "DEF", number: 6 },
  { name: "Andrew Robertson", country: "Scotland", position: "DEF", number: 4 },
  { name: "Nathan Patterson", country: "Scotland", position: "DEF", number: 2 },
  { name: "Greg Taylor", country: "Scotland", position: "DEF", number: 14 },
  { name: "Callum McGregor", country: "Scotland", position: "MID", number: 8 },
  { name: "John McGinn", country: "Scotland", position: "MID", number: 7 },
  { name: "Billy Gilmour", country: "Scotland", position: "MID", number: 16 },
  { name: "Stuart Armstrong", country: "Scotland", position: "MID", number: 10 },
  { name: "Scott McTominay", country: "Scotland", position: "MID", number: 19 },
  { name: "Ryan Christie", country: "Scotland", position: "MID", number: 11 },
  { name: "Che Adams", country: "Scotland", position: "FWD", number: 9 },
  { name: "Lyndon Dykes", country: "Scotland", position: "FWD", number: 20 },
  { name: "Kyogo Furuhashi", country: "Scotland", position: "FWD", number: 17 },
  { name: "Lawrence Shankland", country: "Scotland", position: "FWD", number: 13 },

  // ── SENEGAL ──
  { name: "Édouard Mendy", country: "Senegal", position: "GK", number: 1 },
  { name: "Seny Dieng", country: "Senegal", position: "GK", number: 16 },
  { name: "Cheikhou Kouyaté", country: "Senegal", position: "DEF", number: 4 },
  { name: "Fodé Ballo-Touré", country: "Senegal", position: "DEF", number: 3 },
  { name: "Kalidou Koulibaly", country: "Senegal", position: "DEF", number: 5 },
  { name: "Abdou Diallo", country: "Senegal", position: "DEF", number: 6 },
  { name: "Ismail Jakobs", country: "Senegal", position: "DEF", number: 22 },
  { name: "Pape Abou Cissé", country: "Senegal", position: "DEF", number: 14 },
  { name: "Nampalys Mendy", country: "Senegal", position: "MID", number: 8 },
  { name: "Gana Gueye", country: "Senegal", position: "MID", number: 17 },
  { name: "Pape Gueye", country: "Senegal", position: "MID", number: 18 },
  { name: "Krepin Diatta", country: "Senegal", position: "FWD", number: 11 },
  { name: "Ismaïla Sarr", country: "Senegal", position: "FWD", number: 10 },
  { name: "Sadio Mané", country: "Senegal", position: "FWD", number: 10 },
  { name: "Habib Diallo", country: "Senegal", position: "FWD", number: 9 },
  { name: "Nicolas Jackson", country: "Senegal", position: "FWD", number: 7 },
  { name: "Boulaye Dia", country: "Senegal", position: "FWD", number: 19 },
  { name: "Iliman Ndiaye", country: "Senegal", position: "FWD", number: 20 },

  // ── SOUTH AFRICA ──
  { name: "Ronwen Williams", country: "South Africa", position: "GK", number: 1 },
  { name: "Ricardo Goss", country: "South Africa", position: "GK", number: 23 },
  { name: "Reeve Frosler", country: "South Africa", position: "DEF", number: 2 },
  { name: "Sifiso Hlanti", country: "South Africa", position: "DEF", number: 3 },
  { name: "Rushine De Reuck", country: "South Africa", position: "DEF", number: 5 },
  { name: "Thibang Phete", country: "South Africa", position: "DEF", number: 4 },
  { name: "Teboho Mokoena", country: "South Africa", position: "MID", number: 8 },
  { name: "Bongani Zungu", country: "South Africa", position: "MID", number: 6 },
  { name: "Yusuf Maart", country: "South Africa", position: "MID", number: 16 },
  { name: "Themba Zwane", country: "South Africa", position: "MID", number: 10 },
  { name: "Keagan Dolly", country: "South Africa", position: "FWD", number: 11 },
  { name: "Percy Tau", country: "South Africa", position: "FWD", number: 7 },
  { name: "Lyle Foster", country: "South Africa", position: "FWD", number: 9 },
  { name: "Evidence Makgopa", country: "South Africa", position: "FWD", number: 19 },

  // ── SOUTH KOREA ──
  { name: "Kim Seung-gyu", country: "South Korea", position: "GK", number: 1 },
  { name: "Jo Hyeon-woo", country: "South Korea", position: "GK", number: 12 },
  { name: "Kim Tae-hwan", country: "South Korea", position: "DEF", number: 2 },
  { name: "Kim Young-gwon", country: "South Korea", position: "DEF", number: 4 },
  { name: "Jung Seung-hyun", country: "South Korea", position: "DEF", number: 5 },
  { name: "Kim Jin-su", country: "South Korea", position: "DEF", number: 3 },
  { name: "Kim Min-jae", country: "South Korea", position: "DEF", number: 6 },
  { name: "Lee Jae-sung", country: "South Korea", position: "MID", number: 7 },
  { name: "Jung Woo-young", country: "South Korea", position: "MID", number: 16 },
  { name: "Hwang In-beom", country: "South Korea", position: "MID", number: 8 },
  { name: "Lee Kang-in", country: "South Korea", position: "MID", number: 10 },
  { name: "Paik Seung-ho", country: "South Korea", position: "MID", number: 14 },
  { name: "Son Heung-min", country: "South Korea", position: "FWD", number: 7 },
  { name: "Hwang Hee-chan", country: "South Korea", position: "FWD", number: 11 },
  { name: "Hwang Ui-jo", country: "South Korea", position: "FWD", number: 9 },
  { name: "Cho Gue-sung", country: "South Korea", position: "FWD", number: 19 },
  { name: "Oh Hyeon-gyu", country: "South Korea", position: "FWD", number: 17 },

  // ── SPAIN ──
  { name: "Unai Simón", country: "Spain", position: "GK", number: 1 },
  { name: "David Raya", country: "Spain", position: "GK", number: 13 },
  { name: "Robert Sánchez", country: "Spain", position: "GK", number: 23 },
  { name: "Dani Carvajal", country: "Spain", position: "DEF", number: 2 },
  { name: "Alejandro Balde", country: "Spain", position: "DEF", number: 3 },
  { name: "Robin Le Normand", country: "Spain", position: "DEF", number: 5 },
  { name: "Aymeric Laporte", country: "Spain", position: "DEF", number: 14 },
  { name: "Nacho Fernández", country: "Spain", position: "DEF", number: 4 },
  { name: "Marc Cucurella", country: "Spain", position: "DEF", number: 22 },
  { name: "Pedri", country: "Spain", position: "MID", number: 16 },
  { name: "Gavi", country: "Spain", position: "MID", number: 9 },
  { name: "Rodri", country: "Spain", position: "MID", number: 16 },
  { name: "Fabián Ruiz", country: "Spain", position: "MID", number: 8 },
  { name: "Dani Olmo", country: "Spain", position: "MID", number: 10 },
  { name: "Mikel Merino", country: "Spain", position: "MID", number: 6 },
  { name: "Lamine Yamal", country: "Spain", position: "FWD", number: 19 },
  { name: "Nico Williams", country: "Spain", position: "FWD", number: 11 },
  { name: "Álvaro Morata", country: "Spain", position: "FWD", number: 7 },
  { name: "Ferran Torres", country: "Spain", position: "FWD", number: 20 },
  { name: "Joselu", country: "Spain", position: "FWD", number: 9 },
  { name: "Yeremy Pino", country: "Spain", position: "FWD", number: 17 },

  // ── SWEDEN ──
  { name: "Robin Olsen", country: "Sweden", position: "GK", number: 1 },
  { name: "Karl-Johan Johnsson", country: "Sweden", position: "GK", number: 12 },
  { name: "Emil Krafth", country: "Sweden", position: "DEF", number: 2 },
  { name: "Victor Nilsson Lindelöf", country: "Sweden", position: "DEF", number: 5 },
  { name: "Pontus Jansson", country: "Sweden", position: "DEF", number: 4 },
  { name: "Ludwig Augustinsson", country: "Sweden", position: "DEF", number: 3 },
  { name: "Filip Helander", country: "Sweden", position: "DEF", number: 6 },
  { name: "Kristoffer Olsson", country: "Sweden", position: "MID", number: 8 },
  { name: "Albin Ekdal", country: "Sweden", position: "MID", number: 16 },
  { name: "Dejan Kulusevski", country: "Sweden", position: "MID", number: 10 },
  { name: "Emil Forsberg", country: "Sweden", position: "MID", number: 10 },
  { name: "Mattias Svanberg", country: "Sweden", position: "MID", number: 14 },
  { name: "Alexander Isak", country: "Sweden", position: "FWD", number: 9 },
  { name: "Viktor Gyökeres", country: "Sweden", position: "FWD", number: 11 },
  { name: "Robin Quaison", country: "Sweden", position: "FWD", number: 7 },
  { name: "Anthony Elanga", country: "Sweden", position: "FWD", number: 17 },
  { name: "Jordan Larsson", country: "Sweden", position: "FWD", number: 19 },

  // ── SWITZERLAND ──
  { name: "Yann Sommer", country: "Switzerland", position: "GK", number: 1 },
  { name: "Gregor Kobel", country: "Switzerland", position: "GK", number: 12 },
  { name: "Yvon Mvogo", country: "Switzerland", position: "GK", number: 23 },
  { name: "Silvan Widmer", country: "Switzerland", position: "DEF", number: 2 },
  { name: "Manuel Akanji", country: "Switzerland", position: "DEF", number: 5 },
  { name: "Nico Elvedi", country: "Switzerland", position: "DEF", number: 4 },
  { name: "Ricardo Rodríguez", country: "Switzerland", position: "DEF", number: 13 },
  { name: "Kevin Mbabu", country: "Switzerland", position: "DEF", number: 22 },
  { name: "Granit Xhaka", country: "Switzerland", position: "MID", number: 10 },
  { name: "Remo Freuler", country: "Switzerland", position: "MID", number: 8 },
  { name: "Denis Zakaria", country: "Switzerland", position: "MID", number: 6 },
  { name: "Fabian Frei", country: "Switzerland", position: "MID", number: 16 },
  { name: "Michel Aebischer", country: "Switzerland", position: "MID", number: 17 },
  { name: "Ruben Vargas", country: "Switzerland", position: "FWD", number: 7 },
  { name: "Breel Embolo", country: "Switzerland", position: "FWD", number: 9 },
  { name: "Noah Okafor", country: "Switzerland", position: "FWD", number: 11 },
  { name: "Xherdan Shaqiri", country: "Switzerland", position: "FWD", number: 23 },
  { name: "Kwadwo Duah", country: "Switzerland", position: "FWD", number: 19 },
  { name: "Zeki Amdouni", country: "Switzerland", position: "FWD", number: 14 },

  // ── TUNISIA ──
  { name: "Aymen Dahmen", country: "Tunisia", position: "GK", number: 1 },
  { name: "Bechir Ben Saïd", country: "Tunisia", position: "GK", number: 12 },
  { name: "Dylan Bronn", country: "Tunisia", position: "DEF", number: 5 },
  { name: "Montassar Talbi", country: "Tunisia", position: "DEF", number: 4 },
  { name: "Ali Maaloul", country: "Tunisia", position: "DEF", number: 3 },
  { name: "Wajdi Kechrida", country: "Tunisia", position: "DEF", number: 2 },
  { name: "Nader Ghandri", country: "Tunisia", position: "DEF", number: 6 },
  { name: "Ellyes Skhiri", country: "Tunisia", position: "MID", number: 8 },
  { name: "Aïssa Laïdouni", country: "Tunisia", position: "MID", number: 6 },
  { name: "Youssef Msakni", country: "Tunisia", position: "MID", number: 10 },
  { name: "Wahbi Khazri", country: "Tunisia", position: "MID", number: 19 },
  { name: "Hamza Mathlouthi", country: "Tunisia", position: "MID", number: 14 },
  { name: "Seifeddine Jaziri", country: "Tunisia", position: "FWD", number: 9 },
  { name: "Issam Jebali", country: "Tunisia", position: "FWD", number: 11 },
  { name: "Naïm Sliti", country: "Tunisia", position: "FWD", number: 7 },
  { name: "Sayfallah Ltaief", country: "Tunisia", position: "FWD", number: 17 },

  // ── TURKEY ──
  { name: "Mert Günok", country: "Turkey", position: "GK", number: 1 },
  { name: "Altay Bayındır", country: "Turkey", position: "GK", number: 12 },
  { name: "Merih Demiral", country: "Turkey", position: "DEF", number: 3 },
  { name: "Çağlar Söyüncü", country: "Turkey", position: "DEF", number: 4 },
  { name: "Zeki Çelik", country: "Turkey", position: "DEF", number: 2 },
  { name: "Ferdi Kadıoğlu", country: "Turkey", position: "DEF", number: 14 },
  { name: "Samet Akaydın", country: "Turkey", position: "DEF", number: 5 },
  { name: "Kaan Ayhan", country: "Turkey", position: "MID", number: 6 },
  { name: "Hakan Çalhanoğlu", country: "Turkey", position: "MID", number: 10 },
  { name: "Salih Özcan", country: "Turkey", position: "MID", number: 8 },
  { name: "Orkun Kökçü", country: "Turkey", position: "MID", number: 18 },
  { name: "Yusuf Yazıcı", country: "Turkey", position: "FWD", number: 11 },
  { name: "Kerem Aktürkoğlu", country: "Turkey", position: "FWD", number: 7 },
  { name: "Baris Alper Yilmaz", country: "Turkey", position: "FWD", number: 17 },
  { name: "Burak Yılmaz", country: "Turkey", position: "FWD", number: 9 },
  { name: "Cenk Tosun", country: "Turkey", position: "FWD", number: 19 },
  { name: "Arda Güler", country: "Turkey", position: "MID", number: 20 },

  // ── UNITED STATES ──
  { name: "Matt Turner", country: "United States", position: "GK", number: 1 },
  { name: "Ethan Horvath", country: "United States", position: "GK", number: 12 },
  { name: "Sean Johnson", country: "United States", position: "GK", number: 23 },
  { name: "Sergiño Dest", country: "United States", position: "DEF", number: 2 },
  { name: "Reggie Cannon", country: "United States", position: "DEF", number: 14 },
  { name: "Tim Ream", country: "United States", position: "DEF", number: 5 },
  { name: "Miles Robinson", country: "United States", position: "DEF", number: 4 },
  { name: "John Brooks", country: "United States", position: "DEF", number: 6 },
  { name: "Antonee Robinson", country: "United States", position: "DEF", number: 3 },
  { name: "Joe Scally", country: "United States", position: "DEF", number: 22 },
  { name: "Tyler Adams", country: "United States", position: "MID", number: 4 },
  { name: "Weston McKennie", country: "United States", position: "MID", number: 8 },
  { name: "Yunus Musah", country: "United States", position: "MID", number: 6 },
  { name: "Luca de la Torre", country: "United States", position: "MID", number: 16 },
  { name: "Christian Pulisic", country: "United States", position: "FWD", number: 10 },
  { name: "Timothy Weah", country: "United States", position: "FWD", number: 21 },
  { name: "Ricardo Pepi", country: "United States", position: "FWD", number: 9 },
  { name: "Gio Reyna", country: "United States", position: "FWD", number: 7 },
  { name: "Josh Sargent", country: "United States", position: "FWD", number: 19 },
  { name: "Jordan Morris", country: "United States", position: "FWD", number: 11 },
  { name: "Folarin Balogun", country: "United States", position: "FWD", number: 17 },

  // ── URUGUAY ──
  { name: "Sergio Rochet", country: "Uruguay", position: "GK", number: 1 },
  { name: "Sebastián Sosa", country: "Uruguay", position: "GK", number: 23 },
  { name: "José María Giménez", country: "Uruguay", position: "DEF", number: 2 },
  { name: "Ronald Araújo", country: "Uruguay", position: "DEF", number: 4 },
  { name: "Mathías Olivera", country: "Uruguay", position: "DEF", number: 16 },
  { name: "Diego Godín", country: "Uruguay", position: "DEF", number: 3 },
  { name: "Martín Cáceres", country: "Uruguay", position: "DEF", number: 2 },
  { name: "Rodrigo Bentancur", country: "Uruguay", position: "MID", number: 8 },
  { name: "Federico Valverde", country: "Uruguay", position: "MID", number: 10 },
  { name: "Nicolás De La Cruz", country: "Uruguay", position: "MID", number: 14 },
  { name: "Matías Vecino", country: "Uruguay", position: "MID", number: 15 },
  { name: "Lucas Torreira", country: "Uruguay", position: "MID", number: 6 },
  { name: "Manuel Ugarte", country: "Uruguay", position: "MID", number: 18 },
  { name: "Darwin Núñez", country: "Uruguay", position: "FWD", number: 11 },
  { name: "Luis Suárez", country: "Uruguay", position: "FWD", number: 9 },
  { name: "Facundo Torres", country: "Uruguay", position: "FWD", number: 17 },
  { name: "Maximiliano Gómez", country: "Uruguay", position: "FWD", number: 19 },
  { name: "Edinson Cavani", country: "Uruguay", position: "FWD", number: 21 },

  // ── UZBEKISTAN ──
  { name: "Otabek Shukurov", country: "Uzbekistan", position: "GK", number: 1 },
  { name: "Eldor Shomurodov", country: "Uzbekistan", position: "FWD", number: 9 },
  { name: "Jamshid Iskanderov", country: "Uzbekistan", position: "DEF", number: 4 },
  { name: "Jasur Jaloliddinov", country: "Uzbekistan", position: "MID", number: 8 },
  { name: "Jaloliddin Masharipov", country: "Uzbekistan", position: "MID", number: 10 },
  { name: "Muhammadali Aliboev", country: "Uzbekistan", position: "FWD", number: 7 },
  { name: "Bobur Abdixoliqov", country: "Uzbekistan", position: "FWD", number: 11 },
  { name: "Dostonbek Khamdamov", country: "Uzbekistan", position: "DEF", number: 3 },
  { name: "Sherzod Nishonov", country: "Uzbekistan", position: "DEF", number: 5 },
  { name: "Khurshid Makhmudov", country: "Uzbekistan", position: "MID", number: 14 },
  { name: "Abbosbek Fayzullaev", country: "Uzbekistan", position: "MID", number: 17 },
  { name: "Odiljon Hamrobekov", country: "Uzbekistan", position: "FWD", number: 19 },
  { name: "Botir Shomurodov", country: "Uzbekistan", position: "FWD", number: 20 },
];

async function main() {
  console.log(`Seeding ${players.length} players across all 48 WC2026 teams...`);

  // Wipe existing players and reinsert so this script is idempotent
  await prisma.player.deleteMany({});
  const result = await prisma.player.createMany({ data: players });

  console.log(`Done — created ${result.count} players.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
